export const appConfig = {
  appSlug: 'mezcla-tintas',
  title: 'Mezclador de Tintas de Modelismo',
  emoji: '🎨',
  tagline: 'Consigue cualquier color exacto con tintas de modelismo',
  description: 'Domina la teoría del color para modelismo. Aprende a mezclar Vallejo, AK Interactive y Citadel para obtener cualquier tono con precisión.',
  heroText: '¿Buscas un color específico para tu miniatura o maqueta? Introduce el código HEX y obtén la proporción exacta de gotas en colores primarios.',
  accentColor: '#7C3AED',
  nicheLabel: 'mezcla de tintas',
}

export const articles = [
  {
    slug: 'teoria-color-cmyk-modelismo',
    title: 'CMYK vs RGB: La Teoría del Color que Todo Modelista Debe Conocer',
    content: `<p>Los monitores usan luz (modelo RGB), pero las pinturas mezclan pigmentos (modelo CMYK). Esta diferencia fundamental explica por qué el color que ves en pantalla nunca es exactamente el que obtienes al mezclar pinturas.</p><p>En el modelo <strong>sustractivo CMYK</strong> (Cyan, Magenta, Yellow, Key/Black), cada color absorbe ciertas longitudes de onda de la luz. Al mezclarlos, vas "restando" luz, lo que da colores más oscuros.</p><h4>La regla de las mezclas básicas</h4><ul><li>Cyan + Magenta = Violeta/Púrpura</li><li>Cyan + Yellow = Verde</li><li>Magenta + Yellow = Naranja/Rojo</li><li>Cyan + Magenta + Yellow = Negro (teórico, en práctica marrón sucio)</li></ul><p>Por eso el negro real (Key) se añade como color separado en CMYK: da negros más profundos y permite reducir el consumo de los tres pigmentos principales.</p>`,
  },
  {
    slug: 'marcas-pintura-modelismo-espana',
    title: 'Vallejo, AK Interactive y Citadel: Guía de Marcas para Modelismo en España',
    content: `<p>España es sede de dos de las marcas de referencia mundial en pintura para modelismo: <strong>Vallejo</strong> (Vallejo Model Color, Game Color) y <strong>AK Interactive</strong>. Entender las diferencias entre sistemas te ayuda a mezclar colores compatibles.</p><h4>Principales marcas y sus características</h4><ul><li><strong>Vallejo Model Color:</strong> Base agua. 200+ colores. El estándar para maquetas militares. Gotas perfectamente medibles gracias al gotero.</li><li><strong>Vallejo Game Color:</strong> Base agua. Formulado para colores vivos de miniaturas de fantasía.</li><li><strong>AK Interactive:</strong> Múltiples líneas (Real Colors, 3rd Gen, AMMO). Excelente para efectos de weathering.</li><li><strong>Citadel (Games Workshop):</strong> Base agua. Tarro en lugar de gotero — dificulta la medición exacta. Sistema propio de capas (Base, Layer, Shade, Highlight).</li><li><strong>Andrea Color:</strong> Española también. Especializada en figuras históricas.</li></ul>`,
  },
  {
    slug: 'tecnicas-mezcla-modelismo',
    title: 'Técnicas de Mezcla para Modelismo: Cómo Conseguir el Tono Exacto',
    content: `<p>Mezclar pinturas de modelismo es parte arte, parte química. La clave está en empezar siempre por el color más claro y añadir el oscuro gota a gota — es mucho más fácil oscurecer que aclarar.</p><h4>Protocolo de mezcla profesional</h4><p>1. <strong>Usa una paleta húmeda</strong> para que las pinturas acrílicas no se sequen mientras trabajas.<br/>2. <strong>Empieza por el blanco</strong> si el color final es claro.<br/>3. <strong>Añade el color saturado gota a gota</strong>, mezclando completamente después de cada gota.<br/>4. <strong>Apunta las proporciones</strong> exactas para poder reproducir el color más adelante.<br/>5. <strong>Haz una prueba en papel</strong> antes de aplicar a la miniatura — el color seco es siempre más oscuro que húmedo.</p><h4>Regla del secado</h4><p>Los acrílicos secan 15-20% más oscuros. Si el color te parece correcto en húmedo, probablemente quedará demasiado oscuro. Ajusta adelantando el tono hacia el claro.</p>`,
  },
  {
    slug: 'colores-militares-modelismo',
    title: 'Cómo Conseguir Colores Militares Exactos: Referencias Ral, Federal Standard y Vallejo',
    content: `<p>Los colores militares históricos tienen referencias estandarizadas internacionalmente. Conocer las equivalencias entre sistemas te permite mezclar o encontrar el color correcto para cada vehículo o uniforme.</p><h4>Sistemas de referencia más usados</h4><ul><li><strong>RAL:</strong> Sistema europeo. RAL 7028 = Dark Yellow Alemán WWII. RAL 6003 = Olive Drab.</li><li><strong>Federal Standard 595:</strong> Sistema americano. FS 33105 = Olive Drab US Army.</li><li><strong>Vallejo Model Color:</strong> Tiene su propia numeración (ej: 70.924 = Russian Uniform).</li></ul><h4>Equivalencias clave WWII</h4><ul><li>Dunkelgelb (Amarillo oscuro alemán): RAL 7028 = Vallejo 70.978</li><li>Panzergrau (Gris panzer): RAL 7021 = Vallejo 70.869</li><li>Rotbraun (Rojo marrón): RAL 8017 = Vallejo 70.985</li><li>Olive Drab US: FS 33105 = Vallejo 70.887</li></ul>`,
  },
  {
    slug: 'almacenaje-pinturas-modelismo',
    title: 'Almacenaje y Conservación de Pinturas de Modelismo: Evita que se Sequen',
    content: `<p>Las pinturas acrílicas para modelismo tienen una vida útil de 2-5 años si se almacenan correctamente. Con malas condiciones, pueden secarse en meses.</p><h4>Factores que arruinan las pinturas</h4><ul><li><strong>Temperatura extrema:</strong> No expongas a más de 30°C ni a menos de 5°C. Los ciclos de congelación-descongelación destruyen los aglutinantes.</li><li><strong>Luz solar directa:</strong> Los pigmentos se degradan y decoloran.</li><li><strong>Tapa sucia:</strong> Los restos de pintura en la rosca o gotero se secan y sellan el bote.</li></ul><h4>Trucos de conservación</h4><ul><li>Guarda los botes boca abajo para que el pigmento no se separe del aglutinante.</li><li>Añade 2-3 gotas de agua destilada si la pintura se espesa, no agua del grifo (el cloro la daña).</li><li>Una bolita de acero inoxidable dentro del bote facilita el mezclado.</li><li>Si una pintura está completamente seca, no la tires: disuélvela con retarder y úsala como wash.</li></ul>`,
  },
  {
    slug: 'cmyk-vs-rgb-colores-impresion-pantone',
    title: 'CMYK vs RGB: Por Qué tus Impresiones No Tienen el Color de la Pantalla',
    content: `<p>Llevo toda mi vida profesional en la industria gráfica y puedo afirmarte que la frase más temida por cualquier impresor o serigrafista es siempre la misma: "Ese no es el color de mi logotipo, en mi pantalla se ve mucho más brillante". El conflicto siempre nace de un malentendido tecnológico profundo entre el diseñador aficionado y el taller de impresión. Están intentando comparar dos leyes de la física que son diametralmente opuestas: la luz emitida frente a los pigmentos físicos absorbidos. Educar a tu cliente sobre este fenómeno es la única manera de dejar de tener discusiones interminables sobre las pruebas de color y evitar tener que repetir tiradas enteras de camisetas a tu costa.</p><p>El origen del color determina su saturación y su brillo máximo (Gamut). El modelo RGB (Red, Green, Blue) es el lenguaje nativo de las pantallas de móvil, monitores y televisores. Se crea emitiendo luz directamente hacia tus ojos. Al ser luz pura, puede generar colores fluorescentes, verdes lima eléctricos y azules marinos vibrantes. Por el contrario, el modelo CMYK (Cyan, Magenta, Yellow, Key/Black) es el lenguaje de la imprenta tradicional. Funciona mediante la absorción de luz; la tinta depositada sobre la tela absorbe ciertas ondas de luz del sol y refleja otras. Los pigmentos físicos jamás podrán alcanzar el brillo fosforescente de un píxel iluminado por detrás por un panel LED.</p><h2>El Espacio de Color y la Solución de Tintas Directas</h2><p>El espacio de color RGB es gigantesco, mientras que el espacio CMYK es muchísimo más reducido. Cuando una impresora (o un serigrafista haciendo cuatricromía) intenta reproducir un azul eléctrico brillante RGB usando tintas CMYK, la mezcla de Cyan y Magenta tiende a oscurecerse drásticamente, creando tonos violáceos o marinos apagados y mate.</p><ul><li><strong>La regla de oro del taller:</strong> Nunca apruebes un color crítico a través de una foto por WhatsApp o un PDF visto en la pantalla del móvil del cliente. Exige siempre que el cliente vea una prueba de color física impresa, o indícale que seleccione un código en una guía Pantone sólida de papel (Solid Coated).</li><li><strong>Tintas Directas (Spot Colors):</strong> Si el logotipo del cliente tiene esos colores súper vibrantes que el CMYK oscurece, no puedes usar cuatricromía. Estás obligado a formular una "Tinta Directa" a medida en tu taller. Mezclarás bases pigmentadas puras para crear un bote de ese verde lima exacto, garantizando una vitalidad que el CMYK jamás podría lograr.</li></ul><p><strong>🧮 Transforma las expectativas del cliente en fórmulas químicas reales y exactas. Usa nuestra Calculadora de Mezcla de Tintas. Acceso de por vida por solo 4,99€. Sin suscripción. Pago único vía PayPal. <a href="/checkout">Obtener Acceso Pro →</a></strong></p>`,
  },
  {
    slug: 'como-replicar-color-exacto-meses-despues-archivo',
    title: 'Cómo Replicar el Mismo Color Exacto Meses Después en tu Taller',
    content: `<p>Un taller de serigrafía o impresión se gradúa de amateur a profesional el día que un cliente corporativo habitual llama un año después para pedir una repetición de su pedido, y las camisetas nuevas que le entregas coinciden al 100% en color con las que le vendiste hace doce meses. Confiar en la memoria visual y decir "creo que le puse una espátula de azul y un toque de negro la última vez" es jugar a la ruleta rusa con los colores de marca de tus clientes. La iluminación de tu taller cambia según la hora del día o la estación del año, y tu percepción visual te engañará irremediablemente.</p><p>El archivo de fórmulas de color es la columna vertebral de la retención de clientes. Si un cliente sabe que tú eres el único taller de la ciudad que siempre, sin falta, clava su naranja corporativo, jamás se irá a la competencia por ahorrarse unos céntimos. Pero para lograr esa consistencia, necesitas un sistema de archivo infalible basado en matemáticas, pesos absolutos y muestras físicas curadas que eliminen cualquier rastro de intuición del proceso de mezcla.</p><h2>El Sistema de Archivo Infalible en Tres Fases</h2><p>La repetibilidad exige que documentes las variables antes de limpiar la espátula.</p><ul><li><strong>1. La Fórmula Digital por Porcentajes:</strong> Anota siempre la mezcla por peso exacto en gramos, y luego conviértela a porcentajes. Si anotas "150g de Base, 50g de Rojo", el día que necesites hacer 2 kilos de tinta tendrás que hacer matemáticas complejas. Si lo guardas como "75% Base, 25% Rojo", podrás escalar la fórmula a cualquier tamaño de bote en segundos usando una calculadora.</li><li><strong>2. La Muestra Física (Drawdown):</strong> La tinta líquida en el bote se ve siempre más oscura que la tinta seca. Antes de empezar a imprimir, coge un retazo de la tela exacta que vas a usar (el color del fondo afecta al color de la tinta), imprime un pequeño parche del color, cúralo en el túnel de calor y grápalo físicamente a la ficha de trabajo de papel de ese cliente.</li><li><strong>3. Nunca cambies de proveedor:</strong> Las marcas de tintas plastisol o base agua no son idénticas entre sí. El "Rojo Primario" de la marca A tiene una carga de pigmento y una opacidad distintas al "Rojo Primario" de la marca B. Si en la repetición del pedido intentas usar la fórmula antigua con una marca de tinta nueva, el color fallará. Anota siempre el fabricante en la ficha.</li></ul><p><strong>🧮 Guarda, escala y replica tus fórmulas sin depender de tu memoria visual. Usa nuestra Calculadora de Mezcla de Tintas. Acceso de por vida por solo 4,99€. Sin suscripción. Pago único vía PayPal. <a href="/checkout">Obtener Acceso Pro →</a></strong></p>`,
  },
]