name: Mirror to all repos

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to AdrielRattes/micro-saas-spain
        run: |
          git remote add adriel https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/AdrielRattes-SERVIDORES-WEB/micro-saas-spain.git
          git push adriel main --force

      - name: Push to AdrielRattes/micro-saas-spain-2
        run: |
          git remote add adriel2 https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/AdrielRattes-SERVIDORES-WEB/micro-saas-spain-2.git
          git push adriel2 main --force
